#!/usr/bin/env bash

pkill feh

WALLPAPER_DIR="$HOME/Pictures/wallpaper"
LAST_VIEW_FILE="$HOME/Pictures/wallpaper/last_view.txt"

# Get all image files
IMAGES=($(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o \
    -iname "*.png" -o -iname "*.jpeg" -o -iname "*.svg" \)))

# If no images found, exit
if [ ${#IMAGES[@]} -eq 0 ]; then
    echo "No images found in $WALLPAPER_DIR" >&2
    exit 1
fi

# Pick a random image
RANDOM_IMAGE=${IMAGES[RANDOM % ${#IMAGES[@]}]}

# Set the new wallpaper
feh --bg-scale "$RANDOM_IMAGE"

# Save the selected image to last_view.txt
echo "$RANDOM_IMAGE" > "$LAST_VIEW_FILE"

exit 0

