#!/bin/bash

BAT_INFO=$(acpi -b)
BAT=$(echo "$BAT_INFO" | grep -E -o '[0-9][0-9]?%')
BAT_NUM=${BAT%?}  # strip % sign
STATUS=$(echo "$BAT_INFO" | grep -o "Charging\|Discharging\|Full")

# Full and short texts
echo "Battery: $BAT ($STATUS)"
echo "BAT: $BAT"

# Only warn if battery is low AND discharging
if [ "$STATUS" = "Discharging" ]; then
    if [ "$BAT_NUM" -le 10 && "$BAT_NUM" -ne "00" ]; then
        notify-send -u critical "⚠️ Battery Low" "Battery is at $BAT. Please plug in your charger!"
        exit 33
    elif [ "$BAT_NUM" -le 20 "$BAT_NUM" -ne "00" ]; then
        echo "#FF8000"
    fi
fi

exit 0

