#!/bin/bash

# Get current Bluetooth power status
status=$(bluetoothctl show | grep "Powered" | awk '{print $2}')

# Function to send notification
notify() {
    notify-send "Bluetooth" "$1"
}

# Check and toggle
if [ "$status" == "yes" ]; then
    bluetoothctl power off &>/dev/null
    if [ $? -eq 0 ]; then
        notify "Bluetooth turned OFF"
    else
        notify "Failed to turn OFF Bluetooth"
        exit 1
    fi
else
    bluetoothctl power on &>/dev/null
    if [ $? -eq 0 ]; then
        notify "Bluetooth turned ON"
    else
        notify "Failed to turn ON Bluetooth"
        exit 1
    fi
fi

