#!/usr/bin/env bash

checkCommand() {
    command -v "$1" &> /dev/null
}

setBrightness() {

    local action="$1"

    if checkCommand brightnessctl; then
        case "$action" in
            up)
                brightnessctl set +15% > /dev/null
                ;;
            down)
                brightnessctl set 15%- > /dev/null
                ;;
            *)
                if [[ "$action" =~ ^[0-9]+%$ ]]; then
                    brightnessctl set "$action"
                else
                    cecho "Invalid argument. Use 'up', 'down', or a \
                        percentage (e.g., 50%)." red
                    exit 1
                fi
                ;;
        esac
    else
        cecho "brightnessctl not found." red
        cecho "Installing brightnessctl..." blue
        if sudo pacman -S --noconfirm brightnessctl; then
            setBrightness "$action"
        else
            cecho "Failed to install brightnessctl." red
            exit 1
        fi
    fi
}

if [[ $# -eq 0 ]]; then
    brightnessctl
fi

setBrightness "$1"%

