#!/usr/bin/env bash

# Get current date and time
current_time=$(date +"%H:%M:%S")
current_date=$(date +"%A, %d %B %Y")
arabic_date=$(date +"%Y-%m-%d" --date="TZ=\"Asia/Baghdad\" $(date +'%Y-%m-%d')")

# Additional info
day_info="Today is $(date +'%A'), a great day to achieve your goals!"

# Combine all information
message="⏰ Time: $current_time\n📅 Date: $current_date\n📅 التاريخ العربي: $arabic_date\n\n$day_info"

# Show using zenity
zenity --info --text="$message" --title="Current Time and Date" --width=300 --height=200

