#!/usr/bin/env bash

# for pulsaudion 
pactl load-module module-echo-cancel use_master_format=1 aec_method=webrtc source_name=noise_cancel_source 
pactl set-default-source alsa_output.pci-0000_00_1b.0.analog-stereo.echo-cancel.monitor 






