return {
  -- "nvim-neo-tree/neo-tree.nvim",
  -- lazy = true,
  -- branch = "v3.x",
  -- cmd = { "Neotree" }, -- Load the plugin when the Neotree command is used
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
  --   "MunifTanjim/nui.nvim",
  -- },
  -- config = function ()
  --   require("neo-tree").setup({
  --     window = {
  --       position = "left",
  --       width = 32,
  --       mapping_options = {
  --         noremap = true,
  --         nowait = true,
  --       },
  --     },
  --   })
  -- end
}
