#!/bin/bash

# Usage: ./ch_mac -i <interface> -m <new_mac_address>
# sudo ./ch_mac -i wlan0 -m 02:1A:20:30:4D:53

while getopts "i:m:" opt; do
    case $opt in
        i) interface="$OPTARG" ;;
        m) mac="$OPTARG" ;;
        *) echo "Usage: $0 -i <interface> -m <new_mac_address>" && exit 1 ;;
    esac
done

if [[ -z "$interface" || -z "$mac" ]]; then
    echo "Interface and MAC address are required."
    exit 1
fi

echo "Current MAC address: $(ip link show "$interface" | grep -i "link/ether" | awk '{print $2}')"

echo "Bringing down the interface..."
sudo ip link set "$interface" down

echo "Changing MAC address to $mac..."
sudo ip link set dev "$interface" address "$mac"

echo "Bringing up the interface..."
sudo ip link set "$interface" up

# Verify the change
current_mac=$(ip link show "$interface" | grep -i "link/ether" | awk '{print $2}')

if [[ "${current_mac,,}" == "${mac,,}" ]]; then
    echo "MAC address successfully changed to $current_mac."
else
    echo "Failed to change the MAC address. Current MAC: $current_mac"
    exit 1
fi

