#!/usr/bin/env bash


fzf_cd() {
    # Use fzf to select a directory from the output of find
    folder=$(find "$(pwd)" -type d -print 2>/dev/null | fzf --height 40%)

    # Check if a folder was selected
    if [[ -n "$folder" ]]; then
        return $folder 
    else
        echo "No folder selected." >&2
        return 1
    fi
}
cd fzf_cd
