#!/bin/bash

# Get Bluetooth status
bluetooth_status=$(rfkill list bluetooth | grep -i "Soft blocked" | awk '{print $3}')

# Check if Bluetooth is off
if [[ "$bluetooth_status" == "yes" ]]; then
    echo "off"
    exit 0
fi

# Check for connected devices
connected_device=$(bluetoothctl devices Connected | awk '{$1=$2=""; print substr($0, 3)}')

if [[ -n "$connected_device" ]]; then
    # If a device is connected, display "connect" and the first 5 characters of the device name
    echo "${connected_device:0:10}"
    notify-send -u low -h string:urgency:success "Success" "connected: $connected_device"
else
    # If Bluetooth is on but no device is connected
    echo "not connect"
fi

