#!/usr/bin/env bash

check() {

    # detect the system's package manager
    if grep -qi "arch" /etc/os-release; then
        PKG_MANAGER="pacman -Sy --noconfirm "
        cecho "Detected Arch Linux. Using pacman." green

    elif grep -qi "fedora" /etc/os-release; then
        PKG_MANAGER="dnf install -y"
        cecho "Detected Fedora. Using dnf." green

    else
        PKG_MANAGER="apt-get install -y"
        cecho "Detected Debian/Ubuntu-based system. Using apt." green
    fi

    # Example usage
    cecho "Installing package: $1" blue
    sudo $PKG_MANAGER $1
}

check $1
