#!/usr/bin/bash


vim_checker() {
    # Prompt the user for the Neovim configuration choice
    echo "---- choose the config for nvim ----"
    echo "1- nvim-1 (first config split files-> default)"
    echo "2- nvim_chad (nvim chad)"
    read -r option
    # Define the paths
    config_path="/home/$USER/.config/nvim"
    dotfiles_path="/home/$USER/dotfiles/nvims"
    # Remove any existing Neovim configuration directory
    if [ -d "$config_path" ]; then
        rm -rf "$config_path"
        echo "Existing Neovim configuration removed"
    fi
    # Create the symbolic link based on the user's choice
    case "${option}" in
        1) 
            ln -svf "$dotfiles_path/nvim_lazy_custom" "$config_path"
            #notify-send -u low -h string:urgency:string "Success" "switch: lazy default "
            ;;
        2) 
            ln -svf "$dotfiles_path/nvim_chad" "$config_path" 
            #notify-send -u low -h string:urgency:string "Success" "switch: chad nvim"
            ;;
        *) 
            ln -svf "$dotfiles_path/nvim_lazy_custom" "$config_path" 
            #notify-send -u low -h string:urgency:string "Success" "switch: lazy default"
            ;;
    esac
}
vim_checker
