#!/bin/bash

# Set Wacom tablet settings
for device in stylus eraser touch; do
    device_id=$(xsetwacom --list | grep -i "$device" | awk '{print $8}')
    if [ -n "$device_id" ]; then
        case $device in
            stylus | eraser)
                xsetwacom --set "$device_id" rotate half
                ;;
            touch)
                xsetwacom --set "$device_id" touch off
                ;;
        esac
    fi
done

# Prepare for screencast recording
tmpPID="/tmp/screencast.pid"
outputDir="$HOME/screencast"
mkdir -p "$outputDir"  # Ensure the output directory exists
timeStamp=$(date '+%Y%m%d_%H%M%S')
outputFile="$outputDir/$timeStamp.mp4"

# Get microphone device
mic=$(arecord -l | awk '/USB/ {sub(":", ""); print $2}')

# Stop existing recording if it is running
if [ -s "$tmpPID" ]; then
    kill "$(cat "$tmpPID")" 2>/dev/null
    rm -f "$tmpPID"
fi

# Start new recording with ffmpeg
ffmpeg -framerate 24 -video_size 1920x1080 -f x11grab -i :0 \
       -f alsa -i hw:"$mic" -vcodec libx264 -preset fast -crf 18 -threads 0 \
       -acodec aac -b:a 320k "$outputFile" & echo $! > "$tmpPID"

# Notify dwmblocks to update
pkill -RTMIN+10 dwmblocks

