#!/bin/bash
ICON_FILE="$HOME/.config/redshift_icon"
if [ -f "$ICON_FILE" ]; then
    ICON=$(cat "$ICON_FILE")
    if [ "$ICON" == "sun" ]; then
        echo "🌞"
    else
        echo "🌜"
    fi
else
    echo "🌞"
fi

