#!/usr/bin/bash

echo -e "-> pls enter username for acount : " 
read username
echo -e "-> pls enter path for folder after /home/$username/.... : "
read DirName

sharingFiles() {
  fillPath="/home/${username}/${DirName}"    
  cd $fillPath;
  if ! cd $fillPath ;then
    echo -e "-> Something went wrong during  change Dir!"
    exit 1
  fi
  echo "-> change directory to ${fillPath}"

  files=$(ls)
  echo $files
  # for file in $files; do
  #   echo "-> file name is: $file"
  # done

}
sharingFiles

