#!/usr/bin/bash

# Function to check if a command exists
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Install snapd using yay
checkSnap() {
  if command_exists "snap"; then
    echo -e "->>>> snap is already installed"
  else
    yay -S snapd
  fi


  if [ $? -ne 0 ]; then
    echo -e "-<<<< Failed to install snapd"
    exit 1
  else
    echo -e "->>>> snapd installed successfully"
    # Enable and start the snapd service
    sudo systemctl enable --now snapd.socket
    # Enable classic snap support
    sudo ln -s /var/lib/snapd/snap /snap
    echo -e "->>>> snapd service enalbed and started successfully"
  fi
}
checkSnap

installTodoList() {
  if command_exists "todoist"; then
    echo -e "->>>> todoist is already installed"
  else
    snap install todoist
    if [ $? -ne 0 ]; then
      echo "-<<<< error happend for install todoist"
    else
      echo "->>>> successfuly install todoist"
    fi
  fi
}
installTodoList

installSync() {

#sudo systemctl enable syncthing@yossefPc.service --now
}
