#!/bin/bash

updateAudio() {
   local audio=$(amixer get Master | grep 'Right:' | sed -n 's/.*\[\([0-9]*%\)\].*/\1/p')
   local mute_status=$(amixer get Master | grep 'Right:' | grep -o '\[on\]\|\[off\]')
   
   if [[ $mute_status == "[off]" ]]; then
     echo "Vol: (Muted)"
   else
     echo "Vol: $audio"
   fi
}

updateAudio

# Optionally, you can do the same for dwmblocks if you use it
pkill -SIGUSR1 dwmblocks
