#!/bin/env bash

music_dir="/home/yossef/Music/"
if ! command -v mpv &> /dev/null || ! command -v fzf &> /dev/null; then
    echo "mpv or fzf not found"
    exit 1  
fi


mpc repeat on
SONG=$(find $music_dir -type f \( -iname "*.mp3" -o -iname \
    "*.flac" -o -iname "*.wav" \) | fzf)

if [ -n "$SONG" ]; then
    mpc add "$(realpath --relative-to="$(mpv ls | head -n 1)" "$SONG")"
else
    echo "not vaild"
fi



