#!/bin/bash

# Check if mpv is running
mpv_status=$(playerctl status -p mpv 2>/dev/null)

if [ "$mpv_status" = "Playing" ]; then
    mpv_artist=$(playerctl metadata artist -p mpv)
    mpv_title=$(playerctl metadata title -p mpv)
    echo " $mpv_artist - $mpv_title"
elif [ "$mpv_status" = "Paused" ]; then
    echo " mpv Paused"
else
    echo " No media playing"
fi

