[volume]
command=/home/yossef/.config/i3blocks/volume.sh
interval=2
separator=true
separator_block_width=0

[ipv6]
command=/home/yossef/.config/i3blocks/ipv6.sh
interval=10
separator=true
separator_block_width=0

[wireless]
command=/home/yossef/.config/i3blocks/wireless.sh
interval=5
separator=true
separator_block_width=0

[ethernet]
command=/home/yossef/.config/i3blocks/ethernet.sh
interval=5
separator=true
separator_block_width=0

[battery]
command=/home/yossef/.config/i3blocks/battery.sh
interval=10
separator=true
separator_block_width=0

[cpu_temp]
command=/home/yossef/.config/i3blocks/cpu_temp.sh
interval=5
separator=true
separator_block_width=0

[cpu_usage]
command=/home/yossef/.config/i3blocks/cpu_usage.sh
interval=2
separator=true
separator_block_width=0

[disk]
command=/home/yossef/.config/i3blocks/disk.sh
interval=30
separator=true
separator_block_width=0

[load]
command=/home/yossef/.config/i3blocks/load.sh
interval=5
separator=true
separator_block_width=0

[memory]
command=/home/yossef/.config/i3blocks/memory.sh
interval=5
separator=true
separator_block_width=0

[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1
separator=false
separator_block_width=0
