#!/bin/bash

xwinclass=$(xdotool search --class "$1")
echo "$xwinclass"

if [ -z "$xwinclass" ]; then
    if [ -n "$2" ] && [ -n "$3" ]; then
        kitty --class "$1" --name "$1 _ $3" "$2" "$3"
    else
        kitty --class "$1" --name "$1 _ "
    fi
else
    if [ ! -f "/tmp/$1" ]; then
        touch "/tmp/$1" && xdotool windowunmap "$xwinclass"
    elif [ -f "/tmp/$1" ]; then
        rm "/tmp/$1" && xdotool windowmap "$xwinclass"
    fi
fi

