#!/usr/bin/env bash

RC='\e[0m'
RED='\e[31m'
YELLOW='\e[33m'
GREEN='\e[32m'


install_tmp() {
    dir="$HOME/.tmux/plugins/tpm"
    if [ -d "$dir" ]; then
        echo -e "${GREEN}-- tmp already cloned $dir --${RC}"
    else
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        if [[ $? == 0 ]]; then
            echo -e "${GREEN}-- cloning tmp sucessfuly -- ${RC}"
        else
            echo -e "${RED}** error happend in clone tmp **{RC}"
        fi
    fi
}

install_tmp
