#!/usr/bin/env bash
RC='\e[0m'
RED='\e[31m'
YELLOW='\e[33m'
GREEN='\e[32m'

# insatll yay
install_yay() {
  if _commend_exists yay; then
    echo -e "${GREEN}--- command already exits ----${RC}"
  else
    echo -e "${GREEN}-- install some dependences git base-devel --${RC}"
    pacman -Sy --needed git base-devel
    if [ $? -qe 0 ]; then
      echo -e "${GREEN}-- install yay --${RC}"
      cd
      git clone https://aur.archlinux.org/yay.git
      if [ $? -qe 0 ]; then
        cd yay
        makepkg -si  
        echo -e "${GREEN}-- install yay sucessfuly ---${RC}"
      else
        echo -e "${RED}******** error happend in clone yay *********${RC}"
      fi
    else
      echo -e "${RED}********* error happend in install base-devel ********${RC}"
    fi
  fi
} 

install_yay
