#!/usr/bin/env bash

# change the user name if not found
dotfiles="/home/$USER/dotfiles"

# Function to check if a package is installed
check_and_install() {
    local package="$1"
    
    # Detect the distribution based on presence of key files
    if [ -f /etc/arch-release ]; then
        # Arch Linux
        if pacman -Qi "$package" &>/dev/null; then
            cecho "$package is already installed." green
        else
            cecho "Installing $package with pacman..." blue
            sudo pacman -S --noconfirm "$package"
        fi
    elif [ -f /etc/fedora-release ]; then
        # Fedora
        if rpm -q "$package" &>/dev/null; then
            cecho "$package is already installed." green
        else
            cecho "Installing $package with dnf..." blue
            sudo dnf install -y "$package"
        fi
    elif [ -f /etc/debian_version ]; then
        # Debian/Ubuntu
        if dpkg -s "$package" &>/dev/null; then
            cecho "$package is already installed." green
        else
            cecho "Installing $package with apt-get..." blue
            sudo apt-get update && sudo apt-get install -y "$package"
        fi
    else
        cecho "Unsupported Linux distribution." red
        return 1
    fi
}

install_hyprland_packages() {
    # Check and install Hyprland
    check_and_install hyprland
    
    # Check and install Hyprpaper
    check_and_install hyprpaper
    
    # Check and install Hyprlock
    check_and_install hyprlock
    check_and_install hyprprop
    check_and_install waybar
    check_and_install wl-clipboard xclip
    check_and_install wlroots wayland-utils
    check_and_install wofi
    check_and_install kitty
    check_and_install sddm
}
install_hyprland_packages

cecho "Installation complete!" green
cecho "starting seting the config files" blue

stow_files() {
    cd $dotfiles
    stow hypr
}
stow_files
cecho "finish install" green
