#!/usr/bin/env bash

# Function to check if a package is installed
check_install() {
    PACKAGE=$1
    if ! pacman -Q "$PACKAGE" &>/dev/null; then
        cecho "$PACKAGE is not installed. Installing..." yellow
        yay -S --noconfirm "$PACKAGE"
    else
        cecho "$PACKAGE is already installed." green
    fi
}

# Check and install bluez-utils
check_install bluez-utils

# Check and install bluez
check_install bluez

# Check and install blueman
check_install blueman

# Ensure the Bluetooth service is running
cecho "Ensuring the Bluetooth service is active..." blue
sudo systemctl start bluetooth
sudo systemctl enable bluetooth

# Start the Blueman Manager
cecho "Starting Blueman Manager..." green
blueman-manager

