-- main vim vimtex plugin configuration
return {
    -- {
    --     "lervag/vimtex",
    --     lazy = true,
    --     init = function()
    --         vim.g.vimtex_view_method = "zathura"
    --         vim.g.vimtex_compiler_method = "latexmk"
    --     end,
    -- },
    --
    -- {
    --     "L3MON4D3/LuaSnip",
    --     version = "v2.*",
    --     build = "make install_jsregexp",
    --     event = "InsertEnter",
    --     dependencies = {
    --         "iurimateus/luasnip-latex-snippets.nvim",
    --     },
    --     config = function()
    --         local ls = require("luasnip")
    --
    --         ls.config.set_config({
    --             enable_autosnippets = true,
    --             store_selection_keys = "<Tab>",
    --             updateevents = "TextChanged,TextChangedI",
    --         })
    --
    --         require("luasnip-latex-snippets").setup()
    --
    --         -- make tex snippets also available in markdown/obsidian notes
    --         ls.filetype_extend("markdown", { "tex" })
    --
    --         vim.keymap.set({ "i" }, "<C-k>", function()
    --             if ls.expandable() then
    --                 ls.expand()
    --             end
    --         end, { silent = true, desc = "LuaSnip expand" })
    --
    --         vim.keymap.set({ "i", "s" }, "<C-l>", function()
    --             if ls.jumpable(1) then
    --                 ls.jump(1)
    --             end
    --         end, { silent = true, desc = "LuaSnip jump forward" })
    --
    --         vim.keymap.set({ "i", "s" }, "<C-h>", function()
    --             if ls.jumpable(-1) then
    --                 ls.jump(-1)
    --             end
    --         end, { silent = true, desc = "LuaSnip jump backward" })
    --
    --         vim.keymap.set({ "i", "s" }, "<C-e>", function()
    --             if ls.choice_active() then
    --                 ls.change_choice(1)
    --             end
    --         end, { silent = true, desc = "LuaSnip next choice" })
    --     end,
    -- },
}
